### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ansarizafar** [tumtumtum/Shaolinq#103]
@tumtumtum Shaolinq looks great but there is not much activity from last few months. What is the status of this project. Is this project dead?

**Comment by ansarizafar** [comment]
@asizikov Are you maintaining this project?

**Comment by asizikov** [comment]
no, I'm not a maintainer @ansarizafar.

**Comment by ansarizafar** [comment]
Are you using this project in production?

**Comment by asizikov** [comment]
I've been using it in prod for 4+ years.  I've changed jobs a few month ago, tho.

**Comment by ansarizafar** [comment]
I want to use this project, it looks better than EF core but It seems that the project is not maintained and the maintainer is not active from long time. Do you think its save to use this for a new project?

**Comment by asizikov** [comment]
That depends on your requirements. As long as you don't need to run it on .NET Core/.NET 5 you're good to go with Shaolinq, I guess.

**Comment by ansarizafar** [comment]
Ok. It means the project is dead. Thanks.
