### ISSUE TITLE
Started getting weird exception

### ISSUE THREAD

**Issue by almostEric** [tumtumtum/Shaolinq#77]
Hi,
I recently started getting this exception when calling the BuildDataAccessModel method:
System.MissingMethodException: 'Method not found: 'Void Shaolinq.TypeBuilding.IDataAccessObjectInternal.SetDeflatedPredicate(System.Linq.Expressions.LambdaExpression)'.'
I have tried rolling back all my references to to before May 6th when this started, but I am still getting the error, so I have no idea what is causing it

**Comment by tumtumtum** [comment]
Hi @almostEric. Im sorry about this. Have you tried a clean of the bin directory? Possibly your package versions between Shaolinq and other Shaolinq.* packages are out of sync

**Comment by tumtumtum** [comment]
Also can you let me know if this is happening on .NET or Mono?

**Comment by almostEric** [comment]
Hi Thomas,

 

It is .net 4.5.2 

I’ll try clearing out the bin directories. Also noticed a new version of Npgsql came out today, which seems to force you to do an update as well 😊

 

Eric

**Comment by almostEric** [comment]
…and clearing the bin directory fixed it. Thanks again

**Comment by tumtumtum** [comment]
Great stuff!
